# Promise 是什么
是一种异步解决的方案 比es5传统的解决异步的方案（回调函数）
es6提供了promise对象
# 以前处理异步的方式
```javascript   
// 后者要等待前者执行的结果 f2 要等待 f1执行完
    function f1(callback){
        setTimeout(()=>{
            var res = 'f1'
            console.log('我先执行从后台获取到了f1');
            callback(res)
        },1000)
    }
    function f2(value){
        console.log(value);
    }

    f1(f2)
```
# Promise 详细介绍
![peomise详细介绍](./promise详解.png)
# 基本用法
```javascript   
const promise = new Promise(function(resolve,reject){
        setTimeout(()=>{
            var flag = false;
            flag ? resolve('成功') : reject('失败')
        },1000)
    })

    promise.then(
        (res)=>{console.log(res)},
        (res)=>{console.log(res);
        }

    )
```
# 会立即执行的面试题
```javascript   
 // promise新建后会立即执行
    console.log('hi');
    
    const promise = new Promise(function(resolve,reject){
        console.log('promise');
        resolve()
    })

    promise.then(function(){
        console.log('resolve');
    })

    console.log('hello');
    
```
# 配合原生的ajax实现案例
```javascript   
见代码
```
# Promise.then()
.then方法是定义在原型上的 Promise.prototype
.then之后会返回一个新的promise对象
# Promise.catch()
```javascript
//  const promise = new Promise(function(resolve,reject){
    //      // 第一种
    //     throw new Error('test-error')
    //     // 第二种
    //     try{
    //         throw new Error('test-error')
    //     }catch(e){
    //         reject(e)
    //     }
    // })

    // promise.catch(function(error){console.log(error);
    // })

    // promise已经变成resolve 再抛出错误是无效的
    // const promise = new Promise(function(resolve,reject){
    //     resolve('成功')
    //      // 第一种
    //     throw new Error('test-error')

    // })
    // promise.then(res=>console.log(res)
    // ).catch(function(error){console.log(error);
    // })

    // 错误会一直往下冒
    // const promise = new Promise(function(resolve,reject){
    //     reject('错误')
    // })
    // promise.then(res=>console.log(res)
    // ).catch(function(error){console.log(error);
    // })

    // promise 会吃掉错误
    // 建议用到promise的时候后面一般加上catch捕捉
//     const say = function(){
//         return new Promise(function(resolve,reject){
//             resolve(v+2)
//         })
//     }
//    say().then(()=>{
//        console.log('我是处理后的');
       
//    }).catch(
//        (error)=>{
//         console.log(error)
//         return '123'
//        }
//     ).then((res)=>{
//         console.log(res);
        
//     })
//    setTimeout(()=>{console.log('123456');
//    },1000)

```
# Promise.all()

```javascript   
 // Promise.all 
   // 一次性处理多个promise 生成一个新的promise

   // Promise.all(p1,p2)
   let promise1 = new Promise(function(resolve,reject){
        // resolve('promise11')
        reject('promise11')
   })

   let promise2 = new Promise(function(resolve){
        resolve('promise22')
   })


   Promise.all([promise1,promise2]).then(function(res){
        console.log(res);
   }).catch((res)=>{console.log(res);
   })


```




